jboss-switchyard/switchyard

release/jboss-as7/modules/src/main/resources/external/batik/module.xml

https://issues.jboss.org/browse/SWITCHYARD-2596

SWITCHYARD-2596 Add javax.activation.api as a dependency in xmlgraphics module

---

console/gwt/src/main/java/org/switchyard/console/client/model/State.java
console/gwt/src/main/java/org/switchyard/console/client/ui/service/GatewaysList.java
core/deploy/base/src/main/java/org/switchyard/deploy/BaseServiceHandler.java
core/deploy/base/src/main/java/org/switchyard/deploy/Lifecycle.java

https://issues.jboss.org/browse/SWITCHYARD-1828

SWITCHYARD-1828 Distinguish between binding lifecycle not present and stopped

---

components/bpel/src/main/java/org/switchyard/component/bpel/riftsaw/RiftsawBPELExchangeHandler.java

https://issues.jboss.org/browse/SWITCHYARD-2061

SWITCHYARD-2061 Not possible to deploy WAR SwitchYard application 

---

core/admin/src/main/java/org/switchyard/admin/Application.java
core/admin/src/main/java/org/switchyard/admin/Component.java
core/admin/src/main/java/org/switchyard/admin/SwitchYard.java
core/admin/src/main/java/org/switchyard/admin/base/BaseApplication.java
core/admin/src/main/java/org/switchyard/admin/base/BaseComponent.java
core/admin/src/main/java/org/switchyard/admin/base/BaseSwitchYard.java
core/admin/src/main/java/org/switchyard/admin/base/SwitchYardBuilder.java
core/admin/src/test/java/org/switchyard/admin/base/MessageMetricsCollectionTest.java
core/admin/src/test/java/org/switchyard/admin/base/SwitchYardBuilderTest.java
core/admin/src/test/java/org/switchyard/admin/base/SwitchYardBuilderTestBase.java
core/admin/src/test/resources/switchyard.xml
core/api/src/main/java/org/switchyard/ServiceDomain.java
core/deploy/base/src/main/java/org/switchyard/deploy/BaseServiceHandler.java
core/deploy/base/src/main/java/org/switchyard/deploy/ComponentNames.java
core/deploy/base/src/main/java/org/switchyard/deploy/ServiceDomainManager.java
core/runtime/src/main/java/org/switchyard/internal/DomainImpl.java

https://issues.jboss.org/browse/SWITCHYARD-1694
Moved Rob's pull request here over to the aggregated branch
https://github.com/jboss-switchyard/core/pull/584

SWITCHYARD-1694 Component Service metrics missing from DMR integration

---

components/resteasy/src/main/java/org/switchyard/component/resteasy/util/ClientInvoker.java
components/resteasy/src/main/java/org/switchyard/component/resteasy/util/RESTEasyUtil.java

https://issues.jboss.org/browse/SWITCHYARD-2720

[SWITCHYARD-2720] - Remove end quotes for ACCEPT header in REST Reference bindings

---

release/jboss-as7/extension/src/main/java/org/switchyard/as7/extension/ws/JBossWSEndpoint.java

Adding David's fix anyway, as it enables the jboss-web.xml for sure

SWITCHYARD-2130 change security-domain to != "other" not working

---

components/camel/camel-switchyard/pom.xml
components/clojure/pom.xml
components/common/camel/pom.xml
components/sca/pom.xml
components/test/mixins/jca/pom.xml
core/admin/pom.xml
core/deploy/base/pom.xml
quickstarts/camel-jms-binding/pom.xml
quickstarts/camel-jpa-binding/pom.xml
quickstarts/demos/policy-transaction/pom.xml

https://issues.jboss.org/browse/SWITCHYARD-2837

SWITCHYARD-2837 Change all references to mockito-all to mockito-core

---

components/soap/src/main/java/org/switchyard/component/soap/InboundHandler.java
components/soap/src/main/java/org/switchyard/component/soap/SOAPLogger.java

Fix checkstyle issues and logging format issues introduced.

Fix logging in SOAP InboundHandler.

---

components/resteasy/pom.xml
components/resteasy/src/main/java/org/switchyard/component/resteasy/OutboundHandler.java
components/resteasy/src/main/java/org/switchyard/component/resteasy/util/ClientInvoker.java
components/resteasy/src/main/java/org/switchyard/component/resteasy/util/MethodInvoker.java
components/resteasy/src/test/java/org/switchyard/component/resteasy/util/ClientInvokerTest.java
components/sca/src/main/java/org/switchyard/component/sca/SCAInvoker.java
components/sca/src/test/java/org/switchyard/component/sca/SCAInvokerTest.java

Support overriding endpoint via context property - service name for SCA, URI for REST

SWITCHYARD-1997 Dynamic "per message" endpoint

---

core/transform/src/main/java/org/switchyard/transform/internal/TransformMessages.java
core/transform/src/main/java/org/switchyard/transform/jaxb/internal/JAXBMarshalTransformer.java
core/transform/src/test/java/org/switchyard/transform/jaxb/internal/JAXBTransformerTest.java
core/transform/src/test/java/org/switchyard/transform/jaxb/internal/ObjectFactory.java
core/transform/src/test/java/org/switchyard/transform/jaxb/internal/Order.java

https://issues.jboss.org/browse/SWITCHYARD-2852

SWITCHYARD-2852 SY: JAXB Marshalling should also work without @XmlRootElement

---

bom/pom.xml
pom.xml

Upgrade SwitchYard to use the 6.0.1.Final integration BOM

ENTESB-4962

---

components/bean/src/main/java/org/switchyard/component/bean/ClientProxyBean.java
components/common/camel/src/main/java/org/switchyard/component/camel/common/composer/CamelContextMapper.java
components/common/common/src/main/java/org/switchyard/component/common/composer/BaseRegexContextMapper.java
components/http/src/main/java/org/switchyard/component/http/composer/HttpContextMapper.java
components/jca/src/main/java/org/switchyard/component/jca/composer/IndexedRecordContextMapper.java
components/jca/src/main/java/org/switchyard/component/jca/composer/JMSContextMapper.java
components/jca/src/main/java/org/switchyard/component/jca/composer/MappedRecordContextMapper.java
components/resteasy/src/main/java/org/switchyard/component/resteasy/composer/RESTEasyContextMapper.java
components/soap/src/main/java/org/switchyard/component/soap/composer/SOAPContextMapper.java
components/soap/src/test/java/org/switchyard/component/soap/SOAPGatewayTest.java
core/common/core/src/main/java/org/switchyard/common/property/PropertyConstants.java

https://issues.jboss.org/browse/SWITCHYARD-2828

SWITCHYARD-2828 Enable service independent properties to be carried without need for context mapper

---

components/camel/component/src/test/java/org/switchyard/component/camel/deploy/CamelUriReplacementTest.java
components/camel/component/src/test/resources/org/switchyard/component/camel/deploy/impl-route-uri-replacement.xml
components/camel/component/src/test/resources/org/switchyard/component/camel/deploy/switchyard-uri-replacement-test.xml

https://issues.jboss.org/browse/SWITCHYARD-2876

SWITCHYARD-2876  Write a test for ENTESB-4587

---

release/jboss-as7/modules/src/main/resources/switchyard/components/common/camel/resources/module.xml

https://issues.jboss.org/browse/SWITCHYARD-2895

SWITCHYARD-2895 Please modularize activation classes necessary for email handling

---

release/installer/assembly.xml
release/installer/scripts/installer.ant.xml
release/jboss-as7/bundle/xsl/host.xsl
release/jboss-as7/standalone/dist/assembly-final.xml
release/jboss-as7/standalone/dist/pom.xml
release/jboss-as7/standalone/dist/src/main/resources/host.xml

https://issues.jboss.org/browse/SWITCHYARD-2896

SWITCHYARD-2896 Unresolved dependencies running domain mode

---

components/http/src/main/java/org/switchyard/component/http/HttpGatewayServlet.java
components/resteasy/src/main/java/org/switchyard/component/resteasy/composer/RESTEasyBindingData.java
components/sca/src/main/java/org/switchyard/component/sca/SwitchYardRemotingServlet.java
components/soap/src/main/java/org/switchyard/component/soap/composer/SOAPBindingData.java

https://issues.jboss.org/browse/ENTESB-5283

ENTESB-5283 SecurityServices info should be cached for performance

---

quickstarts/camel-sql-binding/Readme.md
quickstarts/rules-interview-container/Readme.md
quickstarts/rules-interview-dtable/Readme.md

https://issues.jboss.org/browse/SWITCHYARD-2933

SWITCHYARD-2933 camel-sql-binding readme - add wildfly profile to wildfly build instructions

---

release/jboss-as7/wildfly/extension/pom.xml
release/jboss-as7/wildfly/extension/src/main/java/org/switchyard/as7/extension/camel/cxf/HttpServerDestination.java
release/jboss-as7/wildfly/modules/src/main/resources/switchyard/core/module.xml

Added undertow version of HttpServerDestination

SWITCHYARD-2932 camel-cxf-binding does not deploy on WildFly 10

---

components/soap/src/main/java/org/switchyard/component/soap/composer/SOAPContextMapper.java
components/soap/src/test/java/org/switchyard/component/soap/SOAPContextMapperTest.java

https://issues.jboss.org/browse/SWITCHYARD-2969

SWITCHYARD-2969 Property mapping in SOAPContextMapper not working as documented

---

components/soap/src/main/java/org/switchyard/component/soap/endpoint/CXFJettyEndpointPublisher.java

https://jira.jboss.com/browse/ENTESB-6418
@igarashitm Do you think we need to support handlers as well?   That looks significantly more complicated (handler-class, handler-name, soap-role, initParams, soap-header, handler class instantiation).    If so I'll pull this back and add it.

ENTESB-6418 SwitchYard TestRunner should respect jaxws endpoint files

---

core/bus/camel/src/main/java/org/switchyard/bus/camel/CamelMessage.java

https://issues.jboss.org/browse/SWITCHYARD-2979

SWITCHYARD-2979 Transformer invoked from getContent() should also handle Message parameter

---

components/http/src/main/java/org/switchyard/component/http/InboundHandler.java

https://issues.jboss.org/browse/SWITCHYARD-3008

SWITCHYARD-3008 SY InboundHandler does not consider all sources of CharacterEncoding
